##SCRIPT GENERATED BY BRIAN MURITHI ORWE, INTERN SERENA BEACH HOTEL
##IT IS TO AUTOMATE THE PROCESS OF DOING SPEED TESTS WITHOUT NEED FOR A BROWSER
##OF ANY KIND.

import speedtest
import json

#speedtest object
s=speedtest.Speedtest()

#get all speedtest.net servers
servers=s.get_servers()

#hold Kenyan servers in list
kenyan_servers=[]
#hold United Kingdom servers in list
uk_servers=[]
#hold United States servers in list
usa_servers=[]
#Russia servers in list
russia_servers=[]

#display the ones in Kenya
for point in servers:
    server=servers.get(point)
    #get country
    for part in server:
        # get servers that are in kenya
        if part.get('country').find('Kenya')!=-1:
             kenyan_servers.append(part)
             
        #get servers that are in UnitedKingdom
        if part.get('country').find('United Kingdom')!=-1:
            uk_servers.append(part)

        #get servers that are in United States
        if part.get('country').find('United States')!=-1:
            usa_servers.append(part)

        #get servers that are in United States
        if part.get('country').find('Russian Federation')!=-1:
            russia_servers.append(part)


def get_country_servers_by_id(country_servers):
    servers_by_id=[]
    for server in country_servers:
        servers_by_id.append(server.get('id'))

    return servers_by_id

def bytes_to_megabytes(bytes):
    return round((bytes/(10**6)))

print("SERVER IDS",get_country_servers_by_id(kenyan_servers))

s.get_servers(get_country_servers_by_id(kenyan_servers))
s.get_best_server()
s.download()
s.upload()
print(s.results.share())
print("DOWNLOAD: ",bytes_to_megabytes(s.results.download))
print("UPLOAD: ",bytes_to_megabytes(s.results.upload))


"""#specific servers file
with open('specific.json','w') as f:
    f.write(json.dumps(kenyan_servers))"""
  
"""#show all kenyan servers recieved
print("\nKENYAN PROVIDERS: ")
for kenyan_server in kenyan_servers:
    print(kenyan_server.get('sponsor'))

#show all kenyan servers recieved
print("\nUK PROVIDERS: ")
for uk_server in uk_servers:
    print(uk_server.get('sponsor'))

#show all kenyan servers recieved
print("\nUSA PROVIDERS: ")
for usa_server in usa_servers:
    print(usa_server.get('sponsor'))

#show all kenyan servers recieved
print("\nRUSSIAN PROVIDERS: ")
for russia_server in russia_servers:
    print(russia_server.get('sponsor'))

##PUT SERVERS TO JSON
with open('servers.json','w') as serv:
    servers=json.dumps(servers)
    serv.write(servers)
"""
print("DONE")
